### PR TITLE
updating and getting things running again

### PR DESCRIPTION
**Pull request by step21**
- packages updated so that things are running again
- updated web3 version and adapted code for that
- first tries at failing more gracefully if no eth node connection
- at least things are running again / we have a window

### CODE REVIEW

**Comment by d11e9** [comment]
@step21 thanks for submitting this, I made it for personal use, and didnt know if anyone else was using it :)

**Comment by step21** [comment]
@d11e9 thanks :) Well, it isn't all that functional for me yet, but I'd like to see it working.

**Comment by d11e9** [comment]
@step21 yeah its been hard to work on the functionality with a network of 1 peer ;) your interest is welcome. The idea is that all peers voluntarily index and serve requests (searches) for infoHashes they have collected.

**Comment by step21** [comment]
ah right, I assumed you had set up some kind of test network with at least 2 peers. This is what is called Loderunne in the code, right? If I got it correctly, everything is transferred/requested via whisper and hashes are never written to the blockchain, right?

**Pull request merged**
